version: '3'
services:
  node:
    image: 'node:alpine'
    user: 'node'
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    ports:
      - '8080:3000'
    command: 'npm start'
